### ISSUE TITLE
The ecl-dialog overlaps the content of the page

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/oe_theme#24]
### Issue
The ecl-dialog block overlaps the content, because of that impossible to click on any links and etc.

Probably, in this dialog you are trying to display the language switcher. I see it on the top. Check my screenshot.
![screenshot from 2018-02-12 15-22-03](https://user-images.githubusercontent.com/537500/36101847-cb46a1f2-100a-11e8-867d-bc478fb5bc39.png)

Feel free to close it, if you are aware about the issue

**Comment by ademarco** [comment]
Thank you @LOBsTerr ! This will be solved once #23 will be merged.
