### ISSUE TITLE
The comment form fields contain double quotes

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/oe_theme#25]
![screenshot from 2018-02-12 15-22-57](https://user-images.githubusercontent.com/537500/36101900-f19c36b4-100a-11e8-98a9-300116fea06d.png)

**Comment by ademarco** [comment]
Thanks @LOBsTerr ! We are indeed aware of the issue, it is due to TwigJS (used by ECL) not behaving as PHP Twig. This has been fixed in ECL already (see https://github.com/ec-europa/europa-component-library/pull/561) and it will be fixed when #26 will be merged.
